### ISSUE TITLE
'segments' option is not working on Windows

### ISSUE THREAD

**Issue by Alexandre-Du-Lorier** [peteringram0/babel-plugin-console-source#4]
Hey

Thanks for the plugin, it is much appreciated as babel 'meaningful-logs' is a bit too meaningful for me lol.
Though, I am afraid the option 'segments' in the .babelrc is not working for Windows paths as your index.js is splitting '/' and not '\'.

`
 file = state.file.opts.filename.split("/");
`

### Demonstration

`
 ['console-source', {
      segments: 1,
    }],
`

gives me this

`
C:\Users\Temperance\...\server.js (35:4) C:\Users\Temperance\...\server.js (22:4) Server is listening on port 4529
`

(I have replaced full path using '...')

**Comment by peteringram0** [comment]
Thanks for the feedback. Ive added in a custom option for you so you can pass in an option of how you wish to split your path string.

https://github.com/peteringram0/babel-plugin-console-source/releases/tag/2.0.4
